language: python
python:
  - '2.7'
virtualenv:
  system_site_packages: true
before_install:
  - sudo cat /etc/issue.net	
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-dev gfortran python-opencv pkg-config liblapack-dev
  - pip install --upgrade pip
  - pip install Cython
  - travis_wait pip install git+git://github.com/mattloper/chumpy.git
install:
  - pip install -r requirements.txt
script: make test
